# Generated by Django 5.0.6 on 2024-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=100)),
                ('departure_airport', models.CharField(max_length=100)),
                ('departure_airport_code', models.CharField(max_length=10)),
                ('destination', models.CharField(max_length=100)),
                ('destination_airport', models.CharField(max_length=100)),
                ('destination_airport_code', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('destination_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('destination_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=100)),
                ('flight_class', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
