# Generated by Django 5.0.6 on 2024-05-22 04:56

import api.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', api.users.models.UserManager()),
            ],
        ),
    ]
